# Generated by Django 2.0.6 on 2019-05-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch_instance',
            name='box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watch_instance',
            name='image',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='watch_instance',
            name='manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watch_instance',
            name='papers',
            field=models.BooleanField(default=False),
        ),
    ]
