# Generated by Django 2.0.5 on 2018-10-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
