# Generated by Django 2.0.1 on 2018-04-02 04:22

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagecomponentdata',
            name='page_component_id',
        ),
        migrations.AddField(
            model_name='pagecomponent',
            name='data',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='componentdatafield',
            name='component_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentDataFields', to='home.Component'),
        ),
        migrations.AlterField(
            model_name='pagecomponent',
            name='component_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pageComponent', to='home.Component'),
        ),
        migrations.AlterField(
            model_name='pagecomponent',
            name='page_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pageComponent', to='home.Page'),
        ),
        migrations.DeleteModel(
            name='PageComponentData',
        ),
    ]
