# Generated by Django 2.0.1 on 2018-04-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180401_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(blank=True, default='', max_length=120)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
            ],
        ),
    ]
