# Generated by Django 2.0.6 on 2018-09-11 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180911_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='arrival_time',
            field=models.CharField(default=datetime.datetime.now, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(default=datetime.datetime.now, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='leave_time',
            field=models.CharField(default=datetime.datetime.now, max_length=200),
        ),
    ]
