# Generated by Django 2.0.5 on 2018-10-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181009_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='address2',
            new_name='street',
        ),
        migrations.AddField(
            model_name='business',
            name='street2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
