# Generated by Django 2.0.5 on 2018-10-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181009_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
