# Generated by Django 2.0.6 on 2018-09-11 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180911_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecorationListItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.TextField(default='')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decoration_list', to='home.FoodItem')),
            ],
        ),
    ]
