# Generated by Django 2.0.1 on 2018-04-09 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(blank=True, default='', max_length=120)),
                ('text', models.CharField(blank=True, default='', max_length=120)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='home.User')),
            ],
        ),
    ]
