# Generated by Django 2.0.1 on 2018-04-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentdatafield',
            name='attribute_to_change',
            field=models.CharField(blank=True, default='value', max_length=120),
        ),
    ]
