# Generated by Django 2.0.5 on 2018-10-11 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_business_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='deal',
            name='last_published',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='deal',
            name='type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='deal',
            name='valid_until',
            field=models.DateField(null=True),
        ),
    ]
