# Generated by Django 2.0.6 on 2019-05-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_watch_instance_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch_instance',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
