# Generated by Django 2.0.5 on 2018-10-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20181011_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='number_of_redeems_available',
            field=models.IntegerField(default=0),
        ),
    ]
