# Generated by Django 2.0.5 on 2018-09-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180911_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
