# Generated by Django 2.0.6 on 2019-05-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190512_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='reference_number',
            field=models.CharField(db_index=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='watch_instance',
            name='url',
            field=models.CharField(db_index=True, default='', max_length=1000),
        ),
    ]
