# Generated by Django 2.0.6 on 2019-05-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190514_1025'),
    ]

    operations = [
    ]
