# Generated by Django 2.0.1 on 2018-04-22 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_field_model_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field', to='home.Model'),
        ),
    ]
