# Generated by Django 2.0.5 on 2018-10-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_deal_number_of_redeems_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='yelp',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
