# Generated by Django 2.0.5 on 2018-10-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180920_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='guest_count',
            field=models.CharField(default='', max_length=500),
        ),
    ]
