# Generated by Django 2.0.5 on 2018-10-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20181012_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='ask_for_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
