# Generated by Django 2.0.6 on 2019-05-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190514_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicprice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='watch_instance',
            name='price',
        ),
    ]
