# Generated by Django 2.0.5 on 2018-05-27 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_field_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagecomponent',
            old_name='component_id',
            new_name='component',
        ),
    ]
