# Generated by Django 2.0.5 on 2018-05-27 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180526_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentdatafield',
            old_name='component_id',
            new_name='component',
        ),
        migrations.RenameField(
            model_name='pagecomponent',
            old_name='page_id',
            new_name='page',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
    ]
