# Generated by Django 2.0.6 on 2019-05-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190514_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicprice',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='watch_instance',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
