# Generated by Django 2.0.5 on 2018-10-17 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20181017_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.CharField(default=datetime.datetime.now, max_length=200),
        ),
    ]
