# Generated by Django 2.0.5 on 2018-10-30 17:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_remove_home_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('schedule_start_time', models.DateTimeField(null=True)),
                ('length', models.IntegerField(default=30)),
                ('holidays', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_host', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('going', models.BooleanField(default=False)),
                ('want_to_go', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=False)),
                ('last_interaction', models.DateTimeField(default=datetime.datetime.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='home.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('available', models.BooleanField(default=False)),
                ('repeat_monday', models.BooleanField(default=False)),
                ('repeat_tuesday', models.BooleanField(default=False)),
                ('repeat_wednesday', models.BooleanField(default=False)),
                ('repeat_thursday', models.BooleanField(default=False)),
                ('repeat_friday', models.BooleanField(default=False)),
                ('repeat_saturday', models.BooleanField(default=False)),
                ('repeat_sunday', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_times', to='home.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_times', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
