# Generated by Django 2.0.6 on 2018-09-22 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_remove_home_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Company', max_length=255, verbose_name='title')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, help_text='When this project was created.', verbose_name='created')),
                ('updated', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FormElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Radio'), (1, 'Checkbox'), (2, 'Text Input'), (3, 'Paragraph Input'), (4, 'Text Only'), (5, 'Embedded'), (6, 'Image')], default=0)),
                ('order', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('required', models.BooleanField(default=False, help_text='Make the element required when completing the form.')),
                ('pretext', models.TextField(blank=True, help_text='', verbose_name='Pretext')),
                ('posttext', models.TextField(blank=True, help_text='', verbose_name='Posttext')),
                ('data', jsonfield.fields.JSONField()),
                ('display', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('style', models.CharField(blank=True, default='', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, help_text='When this project was created.', verbose_name='created')),
                ('updated', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='updated')),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('answers', jsonfield.fields.JSONField(blank=True, null=True)),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.FormElement')),
            ],
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, help_text='When this submission was created.', verbose_name='created')),
                ('updated', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='updated')),
                ('timestamp', models.BigIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('completedDate', models.DateTimeField(blank=True, null=True)),
                ('answers', jsonfield.fields.JSONField(blank=True, default={}, null=True)),
                ('jsonData', jsonfield.fields.JSONField(blank=True, default={}, null=True)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, help_text='When this project was created.', verbose_name='created')),
                ('updated', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='updated')),
                ('title', models.CharField(default='New project', max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='', verbose_name='Description')),
                ('public', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Company')),
                ('managers', models.ManyToManyField(blank=True, related_name='project_manager', to=settings.AUTH_USER_MODEL)),
                ('masters', models.ManyToManyField(blank=True, related_name='project_master', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, related_name='project_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProjectForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(default='New Form', max_length=200, verbose_name='Title')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, help_text='When this form was created.', verbose_name='created')),
                ('updated', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='updated')),
                ('completed', models.BooleanField(default=False)),
                ('completedDate', models.DateTimeField(blank=True, null=True)),
                ('emailUsers', models.ManyToManyField(blank=True, related_name='form_emails', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='home.Project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ProjectForm'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Submission owner', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='initiator'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Project'),
        ),
        migrations.AddField(
            model_name='formevent',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ProjectForm'),
        ),
        migrations.AddField(
            model_name='formevent',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Event owner', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='initiator'),
        ),
        migrations.AddField(
            model_name='formevent',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.FormSubmission'),
        ),
        migrations.AddField(
            model_name='formelement',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ProjectForm'),
        ),
        migrations.AddField(
            model_name='formelement',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.FormElement'),
        ),
    ]
