# Generated by Django 2.0.5 on 2018-12-30 20:00

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0008_remove_home_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, default='', max_length=120)),
                ('data', jsonfield.fields.JSONField(blank=True, default={})),
                ('order', models.IntegerField()),
            ],
        ),
    ]
