# Generated by Django 2.0.5 on 2018-10-31 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_event_invite_scheduletime'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(default='Book Me', max_length=120),
        ),
    ]
