# Generated by Django 2.0.6 on 2018-09-22 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_project_setup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='masters',
        ),
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
        migrations.AddField(
            model_name='project',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='project_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='project_directors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='field_pros',
            field=models.ManyToManyField(blank=True, related_name='project_field_pros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='supports',
            field=models.ManyToManyField(blank=True, related_name='project_supports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formelement',
            name='posttext',
            field=models.TextField(blank=True, help_text='', verbose_name='Posttext'),
        ),
        migrations.AlterField(
            model_name='formelement',
            name='pretext',
            field=models.TextField(blank=True, help_text='', verbose_name='Pretext'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='project_managers', to=settings.AUTH_USER_MODEL),
        ),
    ]
