# Generated by Django 2.0.5 on 2018-11-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20181016_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='number_of_total_redeems_available',
            field=models.IntegerField(default=0),
        ),
    ]
