# Generated by Django 2.0.5 on 2018-11-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20181126_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='preview_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='preview_order',
            field=models.IntegerField(default=1),
        ),
    ]
