# Generated by Django 2.0.5 on 2018-11-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletime',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
