# Generated by Django 2.0.5 on 2018-09-22 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0010_auto_20180922_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Support Staff', max_length=255)),
                ('markets', models.ManyToManyField(blank=True, related_name='project_user', to='home.Market')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='project',
            name='directors',
        ),
        migrations.RemoveField(
            model_name='project',
            name='field_pros',
        ),
        migrations.RemoveField(
            model_name='project',
            name='managers',
        ),
        migrations.RemoveField(
            model_name='project',
            name='supports',
        ),
        migrations.AlterField(
            model_name='formelement',
            name='posttext',
            field=models.TextField(blank=True, help_text='', verbose_name='Posttext'),
        ),
        migrations.AlterField(
            model_name='formelement',
            name='pretext',
            field=models.TextField(blank=True, help_text='', verbose_name='Pretext'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='', verbose_name='Description'),
        ),
    ]
