# Generated by Django 2.0.5 on 2018-11-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20181127_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='archived',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='preview_archived',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='preview_order',
            field=models.IntegerField(default=0),
        ),
    ]
