# Generated by Django 2.0.1 on 2018-05-30 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180530_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentProp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('type', models.CharField(blank=True, default='', max_length=120)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentProps', to='home.Component')),
            ],
        ),
        migrations.RemoveField(
            model_name='componentprops',
            name='component',
        ),
        migrations.DeleteModel(
            name='ComponentProps',
        ),
    ]
