# Generated by Django 2.0.6 on 2019-05-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190514_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch_instance',
            name='wholesale',
            field=models.BooleanField(default=True),
        ),
    ]
