# Generated by Django 2.0.1 on 2018-06-01 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20180530_1545'),
        ('home', '0011_auto_20180530_1509'),
    ]

    operations = [
    ]
