# Generated by Django 2.0.5 on 2018-11-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_scheduletime_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletime',
            name='timezone',
            field=models.CharField(default='UTC', max_length=120),
        ),
        migrations.AlterField(
            model_name='invite',
            name='last_interaction',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
