# Generated by Django 2.0.5 on 2018-11-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20181127_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customize',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skin_color', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('nipple_color', models.IntegerField(default=0)),
                ('masectomy', models.IntegerField(default=0)),
                ('user', models.IntegerField(default=0)),
            ],
        ),
    ]
