# Generated by Django 2.0.1 on 2018-06-01 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_merge_20180601_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentRequirements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('importStatement', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='example',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='componentrequirements',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentRequirements', to='home.Component'),
        ),
    ]
