# Generated by Django 2.0.5 on 2018-09-22 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20180922_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formelement',
            name='posttext',
            field=models.TextField(blank=True, help_text='', verbose_name='Posttext'),
        ),
        migrations.AlterField(
            model_name='formelement',
            name='pretext',
            field=models.TextField(blank=True, help_text='', verbose_name='Pretext'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Project'),
        ),
    ]
