# Generated by Django 2.0.5 on 2018-11-10 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
