# Generated by Django 2.0.5 on 2018-11-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_customize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=1200)),
                ('type', models.CharField(blank=True, default='', max_length=120)),
                ('phone', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('next_appointment', models.DateField(null=True)),
                ('reminder', models.BooleanField(default=False)),
                ('user', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, default='', max_length=1200)),
                ('answer', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(blank=True, default='', max_length=1200),
        ),
    ]
