# Generated by Django 2.0.6 on 2019-05-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_watch_instance_wholesale'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch_instance',
            name='info',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
