# Generated by Django 2.0.5 on 2018-11-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_follow_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='fine_print',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deal',
            name='what_you_get',
            field=models.TextField(blank=True, default=''),
        ),
    ]
