# Generated by Django 2.0.6 on 2018-09-23 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20180922_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formelement',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='searchTerm',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='formelement',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='home.ProjectForm'),
        ),
        migrations.AlterField(
            model_name='formelement',
            name='posttext',
            field=models.TextField(blank=True, help_text='', verbose_name='Posttext'),
        ),
        migrations.AlterField(
            model_name='formelement',
            name='pretext',
            field=models.TextField(blank=True, help_text='', verbose_name='Pretext'),
        ),
        migrations.AlterField(
            model_name='formelement',
            name='type',
            field=models.IntegerField(choices=[(0, 'Radio'), (1, 'Checkbox'), (2, 'Text Input'), (3, 'Paragraph Input'), (4, 'Text Only'), (5, 'Image')], default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='', verbose_name='Description'),
        ),
    ]
