# Generated by Django 2.0.5 on 2018-11-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20181129_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='archived',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faq',
            name='preview_archived',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='preview_order',
            field=models.IntegerField(default=0),
        ),
    ]
