# Generated by Django 2.0.1 on 2018-06-01 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20180601_1020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComponentRequirements',
            new_name='ComponentRequirement',
        ),
    ]
