# Generated by Django 2.0.5 on 2018-11-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20181112_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='business',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
