# Generated by Django 2.0.6 on 2019-08-31 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0014_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=1000)),
                ('phone', models.CharField(default='', max_length=1000)),
                ('email', models.CharField(default='', max_length=1000)),
                ('reference_number', models.CharField(default='', max_length=1000)),
                ('min_price', models.FloatField(default=0.0)),
                ('max_price', models.FloatField(default=0.0)),
                ('notes', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='watchrequest',
            name='watch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='watch_request', to='home.Watch'),
        ),
    ]
