# Generated by Django 2.0.5 on 2018-11-30 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20181129_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.IntegerField(default='')),
                ('user', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x_coord', models.IntegerField(default=0)),
                ('y_coord', models.IntegerField(default=0)),
                ('symptom', models.CharField(default='', max_length=120)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='home.Journal')),
            ],
        ),
    ]
