# Generated by Django 2.0.7 on 2018-08-15 21:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0014_auto_20180601_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('score', models.CharField(default='', max_length=200)),
                ('conflict_score', models.CharField(default='', max_length=200)),
                ('comment', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sid', models.IntegerField(default=0)),
                ('response', models.TextField(default='')),
                ('active_analyses', models.IntegerField(default=0)),
                ('last_completed_analysis', models.DateTimeField(default=datetime.datetime.now)),
                ('completed_analyses', models.IntegerField(default=0)),
                ('analysis_conflict', models.BooleanField(default=False)),
                ('admin_answer', models.CharField(default='', max_length=200)),
                ('admin_comment', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(default='')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='home.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('text', models.TextField(default='')),
                ('options', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('analyses_per_response', models.IntegerField(default=2)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='componentprop',
            name='component',
        ),
        migrations.RemoveField(
            model_name='componentrequirement',
            name='component',
        ),
        migrations.RemoveField(
            model_name='field',
            name='model',
        ),
        migrations.RemoveField(
            model_name='pagecomponent',
            name='component',
        ),
        migrations.RemoveField(
            model_name='pagecomponent',
            name='page',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='View',
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='ComponentProp',
        ),
        migrations.DeleteModel(
            name='ComponentRequirement',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='PageComponent',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='test',
            name='users',
            field=models.ManyToManyField(related_name='tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='home.Test'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='home.Question'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='home.Answer'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL),
        ),
    ]
