# Generated by Django 2.0.6 on 2018-08-28 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20180601_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentprop',
            name='component',
        ),
        migrations.RemoveField(
            model_name='componentrequirement',
            name='component',
        ),
        migrations.RemoveField(
            model_name='field',
            name='model',
        ),
        migrations.RemoveField(
            model_name='pagecomponent',
            name='component',
        ),
        migrations.RemoveField(
            model_name='pagecomponent',
            name='page',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='View',
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='ComponentProp',
        ),
        migrations.DeleteModel(
            name='ComponentRequirement',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='PageComponent',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
