# Generated by Django 2.0.6 on 2018-09-23 21:46

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20180923_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formsubmission',
            old_name='answers',
            new_name='data',
        ),
        migrations.AlterField(
            model_name='formelement',
            name='data',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='formelement',
            name='posttext',
            field=models.TextField(blank=True, help_text='', verbose_name='Posttext'),
        ),
        migrations.AlterField(
            model_name='formelement',
            name='pretext',
            field=models.TextField(blank=True, help_text='', verbose_name='Pretext'),
        ),
        migrations.AlterField(
            model_name='formevent',
            name='answers',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='home.ProjectForm'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='searchTerm',
            field=models.CharField(default='New Submission', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='', verbose_name='Description'),
        ),
    ]
