# Generated by Django 2.0.5 on 2018-11-30 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_journal_symptom'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
