# Generated by Django 2.0.7 on 2018-08-08 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20180807_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='test',
        ),
    ]
