# Generated by Django 2.0.5 on 2018-09-23 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20180923_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Market'),
        ),
        migrations.AlterField(
            model_name='formelement',
            name='posttext',
            field=models.TextField(blank=True, help_text='', verbose_name='Posttext'),
        ),
        migrations.AlterField(
            model_name='formelement',
            name='pretext',
            field=models.TextField(blank=True, help_text='', verbose_name='Pretext'),
        ),
        migrations.AlterField(
            model_name='formelement',
            name='type',
            field=models.IntegerField(choices=[(0, 'Radio'), (1, 'Checkbox'), (2, 'Text Input'), (3, 'Number Input'), (4, 'Paragraph Input'), (5, 'Text Only'), (6, 'Image')], default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='', verbose_name='Description'),
        ),
    ]
