# Generated by Django 2.0.5 on 2018-11-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20181113_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='ad',
            field=models.BooleanField(default=False),
        ),
    ]
