# Generated by Django 2.0.7 on 2018-08-17 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0015_auto_20180815_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('domain_name', models.CharField(blank=True, default='', max_length=1200)),
                ('name', models.CharField(blank=True, default='', max_length=1200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmojiSlider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prompt', models.CharField(blank=True, default='', max_length=120)),
                ('progress_bar_color', models.CharField(blank=True, default='', max_length=120)),
                ('background_color', models.CharField(blank=True, default='', max_length=120)),
                ('text_color', models.CharField(blank=True, default='', max_length=120)),
                ('emoji', models.CharField(blank=True, default='', max_length=240)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emoji_slider', to='home.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='SliderAnswers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, default='', max_length=120)),
                ('value', models.IntegerField(default=0)),
                ('emoji_slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_answers', to='home.EmojiSlider')),
            ],
        ),
        migrations.CreateModel(
            name='SliderImpressions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, default='', max_length=120)),
                ('emoji_slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_impressions', to='home.EmojiSlider')),
            ],
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='user',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.RemoveField(
            model_name='test',
            name='users',
        ),
        migrations.DeleteModel(
            name='Analysis',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Discussion',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
