# Generated by Django 2.0.6 on 2019-08-31 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0015_auto_20190831_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceMove',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_average_price', models.FloatField(default=0.0)),
                ('current_average_price', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pricemove',
            name='watch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_move', to='home.Watch'),
        ),
    ]
