# Generated by Django 2.0.7 on 2018-08-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20180817_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideranswers',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sliderimpressions',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
