# Generated by Django 2.0.6 on 2018-09-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20180923_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectform',
            name='isTemplate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formelement',
            name='posttext',
            field=models.TextField(blank=True, help_text='', verbose_name='Posttext'),
        ),
        migrations.AlterField(
            model_name='formelement',
            name='pretext',
            field=models.TextField(blank=True, help_text='', verbose_name='Pretext'),
        ),
        migrations.AlterField(
            model_name='formelement',
            name='type',
            field=models.IntegerField(choices=[(0, 'Radio'), (1, 'Checkbox'), (2, 'Text Input'), (3, 'Number Input'), (4, 'Paragraph Input'), (5, 'Text Only'), (6, 'Address')], default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='', verbose_name='Description'),
        ),
    ]
