# Generated by Django 2.0.6 on 2018-08-30 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_create_project_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['number']},
        ),
        migrations.RemoveField(
            model_name='article',
            name='pages',
        ),
        migrations.AddField(
            model_name='article',
            name='endPage',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='articleEndings', to='home.Page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='startPage',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='home.Page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='home.Tag'),
        ),
    ]
