# Generated by Django 2.0.5 on 2018-11-30 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_journal_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='notes',
        ),
    ]
