# Generated by Django 2.0.6 on 2018-08-30 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20180830_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='LargeText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='home.Tag'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textArticles', to='home.LargeText'),
        ),
        migrations.AlterField(
            model_name='page',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.LargeText'),
        ),
        migrations.AddField(
            model_name='article',
            name='html',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='htmlArticles', to='home.LargeText'),
            preserve_default=False,
        ),
    ]
