# Generated by Django 2.0.7 on 2018-08-09 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20180808_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='active_analyses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='analysis_conflict',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='completed_analyses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='last_completed_analysis',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
