# Generated by Django 2.0.6 on 2018-08-31 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20180830_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='html',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='htmlArticles', to='home.LargeText'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='textArticles', to='home.LargeText'),
        ),
    ]
