# Generated by Django 2.0.5 on 2018-11-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_journal_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
