# Generated by Django 2.0.7 on 2018-08-09 19:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0018_auto_20180809_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='users',
            field=models.ManyToManyField(related_name='tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
