# Generated by Django 2.0.6 on 2018-09-06 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20180831_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='chapter',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='home.Article'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='endPage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapterEndings', to='home.Page'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='html',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='htmlChapters', to='home.LargeText'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='startPage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='home.Page'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='chapters', to='home.Tag'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='textChapters', to='home.LargeText'),
        ),
    ]
