# Generated by Django 2.0.7 on 2018-08-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20180809_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='admin_answer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='answer',
            name='admin_comment',
            field=models.TextField(default=''),
        ),
    ]
