# Generated by Django 2.0.5 on 2018-12-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20181209_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='notifications_token',
            field=models.CharField(blank=True, default='', max_length=1200),
        ),
    ]
