# Generated by Django 2.0.7 on 2018-08-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20180810_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='conflict_score',
            field=models.CharField(default='', max_length=200),
        ),
    ]
