# Generated by Django 2.0.6 on 2018-09-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20180905_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='number',
            field=models.CharField(default='', max_length=200),
        ),
    ]
