# Generated by Django 2.0.5 on 2018-12-11 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_usersettings_notifications_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='uuser',
            new_name='user',
        ),
    ]
