# Generated by Django 2.0.5 on 2018-12-12 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='timezone_offset',
            field=models.IntegerField(default=0),
        ),
    ]
