# Generated by Django 2.0.5 on 2018-12-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_usersettings_timezone_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='breast_exam_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='email_newsletters',
            field=models.BooleanField(default=True),
        ),
    ]
