# Generated by Django 2.0.5 on 2018-12-15 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20181214_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='country_of_origin',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='gynocologist_reminder',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='last_menstruation_day',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='mammogram_reminder',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='physical_reminder',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='reminder_day',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
