# Generated by Django 2.0.6 on 2019-03-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelWebsite', '0005_auto_20190210_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconfig',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
