# Generated by Django 2.0.6 on 2019-04-12 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelWebsite', '0006_pagegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='pagegroup',
            field=models.ForeignKey(default='e10b45fa-e37a-41b5-a003-86728149bc90', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='modelWebsite.PageGroup'),
        ),
    ]
