# Generated by Django 2.0.6 on 2019-04-12 21:32

from django.db import migrations, models
import uuid

def create_base_pages(apps, schema_editor):
    Pages = apps.get_model("modelWebsite", "Page")

    master_pages = Pages.objects.using('cm').all()
    print ("\n\n\n\n", "Here", "\n\n\n\n")

    for page in master_pages:
        print ("\n\n\n\n","Page", page.name,"\n\n\n\n")
        new_page = Pages()
        new_page.name = page.name
        new_page.url = page.url
        new_page.components = page.components
        new_page.componentProps = page.componentProps
        new_page.pagegroup = page.pagegroup
        new_page.save(using='default')



class Migration(migrations.Migration):

    dependencies = [
        ('modelWebsite', '0007_page_pagegroup'),
    ]

    operations = [
        migrations.RunPython(create_base_pages)
    ]
