# Generated by Django 2.0.1 on 2018-01-15 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('username', models.SlugField(unique=True, verbose_name='username')),
                ('type', models.CharField(choices=[('User', 'User'), ('Parent', 'Parent')], default='User', max_length=7)),
                ('newsletter', models.BooleanField(default=False, help_text='Subscribe to newsletter.', verbose_name='newsletter')),
                ('invited_others', models.BooleanField(default=False, verbose_name='invited others')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('updated', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='deleted')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
