# Generated by Django 2.0.1 on 2018-02-01 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='invited_others',
        ),
        migrations.RemoveField(
            model_name='user',
            name='newsletter',
        ),
    ]
