# Generated by Django 2.0.1 on 2018-02-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180131_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_genre_id',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='last_subgenre_ids',
            field=models.CharField(default='', max_length=120),
        ),
    ]
