# Generated by Django 2.0.1 on 2018-03-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180208_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_song_id',
            field=models.CharField(default='', max_length=120),
        ),
    ]
