# Generated by Django 2.0.1 on 2018-04-09 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_last_song_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_genre_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_song_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_subgenre_ids',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
