# Generated by Django 2.0.1 on 2018-04-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180408_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imageUrl',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
