# Generated by Django 2.0.5 on 2018-12-30 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
    ]
