# Generated by Django 2.0.5 on 2018-11-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='set_up',
            field=models.BooleanField(default=False),
        ),
    ]
